### ISSUE TITLE
ngadmin error

### ISSUE THREAD

**Issue by quickstreamingmedia** [MAGOWARE/backoffice-administration#1]
Error: Response for getList SHOULD be an array and not an object or something else

this  system  is not working proper and where is app source

**Comment by saimirg** [comment]
https://github.com/MAGOWARE/backoffice-administration/issues/1

**Comment by quickstreamingmedia** [comment]
fine on local system but problem in server

**Comment by glalaj** [comment]
From the error, I assume your are using Restangular (and its method getList() ). 
If that is the case, the error happens because our middleware returns responses as objects, while getList expects them as arrays.

**Comment by glalaj** [comment]
This error suggests that you are expecting the response as an array, while our middleware returns it as an object. However, I am going to need more details about the API where you get this error.
