### ISSUE TITLE
Login not working on firefox and safari

### ISSUE THREAD

**Issue by nileshlets** [MAGOWARE/backoffice-administration#12]
I have installed magoware successfully and it is working fine.
When I try to login in chrome it works fine. But when i try to login using firefox or safari it redirets back me to login page. 
When i enter wrong password it shows error so it is fine but with right password it redirects me back on login page without any error message.
Can you please look into this issue and let me know the solution?

**Comment by irisstaro** [comment]
Hello!
On other browsers , accept chrome, there is a redirection to the login page. We are working on resolving this issue and soon will publish a new version of backoffice.
To login to mozilla or other browsers , after logging in and redirection to the login page, please delete the last part of url #/login and press enter. Automatically you will access the dashboard

Thanks
