### ISSUE TITLE
Initial login issue

### ISSUE THREAD

**Issue by LifeOfBrianOC** [MAGOWARE/backoffice-administration#16]
Hi,
I have installed backoffice ok but when i try to login with the default user/password of admin/admin i get redirected back to the login page. I tried the solution here https://github.com/MAGOWARE/backoffice-administration/issues/12 but got the same result in all browsers. Appreciate any advice you can give.

**Comment by irisstaro** [comment]
Hello,
Can you please send us logs from the server when you try to login to check the problem ?

Thanks
