### ISSUE TITLE
Unable To Connect To Databace

### ISSUE THREAD

**Issue by Sonofmarske** [MAGOWARE/backoffice-administration#18]
I have created a database and I have triple checked my Creds for access and I have the correct port. but after a while, it presents the error message unable to connect to the database. please, can you help me? I have already tried the existing solution

**Comment by irisstaro** [comment]
Hello!
Are you using MySQL ? 
Also , what type of server are you using ?

**Comment by Sonofmarske** [comment]
I am using MariaDB

**Comment by irisstaro** [comment]
Hello!
Please uninstall the mariadb and install MySQL , for the moment we support only MySQL 
After that try a fresh installation of Magoware

**Comment by Sonofmarske** [comment]
Ok Thanks

**Comment by rtirak** [comment]
I also have this issue. I am using mysql and I get Error connecting to database

**Comment by hungphidev** [comment]
@rtirak You should check your IP and Port of MySQL Server in ../config/env/db.connection.js; Make sure username and password of MySQL are correct.
If you install Magoware and MySQL in same server, your MySQL IP should be 0.0.0.0 or 127.0.0.1 based on your my.cnf.

**Comment by rtirak** [comment]
Thanks I was able to figure out the issue. It was a permissions problem.

**Comment by sazzam2** [comment]
Having the same issue here and I have already made sure that ./config/env/db.connection.js is accurate so I am not sure what to do from here? Can you please assist? 

<img width="1228" alt="11111" src="https://user-images.githubusercontent.com/33765573/50465672-ed52af80-0955-11e9-884f-b1b8d2c23d0c.PNG">

**Comment by graseuser** [comment]
> Having the same issue here and I have already made sure that ./config/env/db.connection.js is accurate so I am not sure what to do from here? Can you please assist?
> 
> <img alt="11111" width="1228" src="https://user-images.githubusercontent.com/33765573/50465672-ed52af80-0955-11e9-884f-b1b8d2c23d0c.PNG">

Try This commande in mysql it solve my probleme
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'

**Comment by shafwanaw** [comment]
where can I change the problem file
![ECONNREFUSED](https://user-images.githubusercontent.com/56389137/68098279-631c9580-feee-11e9-9af2-e55c4547acac.png)
