### ISSUE TITLE
Can not Open TV Channels > Category / Genre: ng-admin getList error.

### ISSUE THREAD

**Issue by hungphidev** [MAGOWARE/backoffice-administration#19]
An Error happened in Category / Genre function. The console show me:
`ng-admin.min.js:19214 Error: Response for getList SHOULD be an array and not an object or something else
    at q (ng-admin.min.js:40813)
    at processQueue (ng-admin.min.js:21528)
    at ng-admin.min.js:21544
    at Scope.$eval (ng-admin.min.js:22790)
    at Scope.$digest (ng-admin.min.js:22606)
    at Scope.$apply (ng-admin.min.js:22898)
    at ng-admin.min.js:23194
    at completeOutstandingRequest (ng-admin.min.js:12180)
    at ng-admin.min.js:12457`

It not work even try to reset project and apply solution below [https://stackoverflow.com/questions/22012655/restangular-getlist-with-object-containing-embedded-array](url)

Please help me!

**Comment by glalaj** [comment]
Is this your first installation of the middleware, or an update? If it is an update, make sure that you have executed the latest migration files successfully.

If the problem persists, please post the response of the API for this request. 
I assume you are using an inspecting tool. In the network menu you can see the response for every request. The request you should be looking for is **/api/Genres?_end=30&_orderBy=id&_orderDir=DESC&_start=0**

**Comment by hungphidev** [comment]
@glalaj Thanks for reply!
This is my first installation but I also run `sequelize db:migrate` command and it successfully. 

The response of API you provide **http://localhost:8011/api/Genres?_end=30&_orderBy=id&_orderDir=DESC&_start=0**
`{
"message": "User is not allowed"
}`

RESPONSE CODE is **403 Forbidden**

**Comment by hungphidev** [comment]
Hi @glalaj, I logged using account admin in Administration Group by default. I also set full permission for this group below.
-------- PICTURE: 
![image](https://user-images.githubusercontent.com/31460470/42792763-1a5a1d90-89a1-11e8-8f60-fa89b8e25fc2.png)

I try to create another user and set read permission but it error also appeared.

**Comment by glalaj** [comment]
Sorry for the late reply. 
If you are still working on the issue, try the new update that was released.
To troubleshoot the problem, connect to a new database schema. During the first start keep track of the logs for the tables created. There should be no error generated (especially for the table api_url which is related to the API permissions).
If an error is generated please post it in this thread.

**Comment by hungphidev** [comment]
Thanks @glalaj it solved my issue when updated new release!

**Comment by bojko91** [comment]
{
    "message": "User is not allowed"
}

When I try to change from API pin code ( localhost/api/logindata/:IDNUMB  with metod PUT ). In header I put token that is given to me from ( localhost/api/auth) like this (key: auth value: TOKEN). But stills give me 403forbiden and this USER IS NOT ALLOWED.  From http://localhost/admin/#/Groups/edit/2  i allow everything. Fresh new instalation from today!
