### ISSUE TITLE
"Undefined" response on click of login button

### ISSUE THREAD

**Issue by Irshadkhan786** [MAGOWARE/backoffice-administration#20]
![d880cfd1-9f7c-40ba-94ef-38bb7e21f8b6](https://user-images.githubusercontent.com/16083313/42676356-7bd01ebc-8695-11e8-9908-745d1d38906f.jpg)
Hi ,

Everything i have done but i am getting undefined response when i click on login button.

**Comment by irisstaro** [comment]
Hello!

Can you please send us the logs of the installation ? When you run  the first time the server , did you get any error ?

Thanks

**Comment by AlbertEinsteinGlitchPoint** [comment]
your instalation was not complete, please make re-do full instalation steps..

**Comment by irisstaro** [comment]
Hello Albert!

Were you able to install the management system ?

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi irisstaro

yes my instalation was ok i was just replying for issue of friend before, i had same thing on first initial install but was resolved by installing it all over again

**Comment by irisstaro** [comment]
Okay , thank you for your reply. You can contact us at support@magoware.tv for any assistance needed
