### ISSUE TITLE
problem ne hapjen e Genres/List apo krijimin Channels/create

### ISSUE THREAD

**Issue by klobes** [MAGOWARE/backoffice-administration#23]
per te ndihmuar ndonje qe ka veshtiresi ne krijim e kanaleve(Channels/create) apo per te pare zhanerat(Genres  List)
zgjidhja : 
mbasi logohet si root ne mysql 
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

e lehte eee..
nje falenderim dhe per stafin opensource

**Comment by glalaj** [comment]
@klobes thanks for your contribution on the repository. 
If there is a specific issue with the creation of channels or genre list, could you provide more info? What is the version number of the faulty code? Does it throw an error or return a specific response? Was it a fresh install or an update?

**Comment by klobes** [comment]
on fresh install of Ubuntu 16.04 by default MySQL not allow queue by FULL_GROUP_BY
browsing web http://xx.xx.xx.xx/admin/#/Genres/list, and /admin/#/Channels/create
erro description on console : 
ng-admin.min.js:19214 Error: Response for getList SHOULD be an array and not an object or something else
    at q (ng-admin.min.js:40813)
    at processQueue (ng-admin.min.js:21528)
    at ng-admin.min.js:21544
    at Scope.$eval (ng-admin.min.js:22790)
    at Scope.$digest (ng-admin.min.js:22606)
    at Scope.$apply (ng-admin.min.js:22898)
    at ng-admin.min.js:23194
    at completeOutstandingRequest (ng-admin.min.js:12180)
    at ng-admin.min.js:12457
(anonymous) @ ng-admin.min.js:19214

you are welcome to help

**Comment by glalaj** [comment]
Alternatively you can also use the default sql mode (No_ENGINE_SUBSTITUTION)
