### ISSUE TITLE
backend-office add support for another language pack

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [MAGOWARE/backoffice-administration#24]
hi

i am having troubles finding the correct files and folders for language pack translation, i am trying to translate to Portuguese but only found 2 files for translation .json which i created a new one for pt.json

but the full backend-office menus i have not found the files

also, the header.html i have added on the drop-down menu list the new language name definition ptbr... but after restart server nmp.. still only show up the 4 languages previously selected.

can you please guide me on which file and folder i need to play around for adding extra-language pack support

**Comment by irisstaro** [comment]
Hi Albert!

Please send us the translated string file and we will include it on the management system

**Comment by AlbertEinsteinGlitchPoint** [comment]
hi please closing topic fixed language pack translation
