### ISSUE TITLE
why not upgrade version of ng-admin 

### ISSUE THREAD

**Issue by yaminipanchal** [MAGOWARE/backoffice-administration#26]
Hello, @glalaj 

As I can see, right now "MAGOWARE" using 0.0.2 version of "ng-admin-demo" and "ng-admin-demo" is using  "ng-admin": "1.0.0-RC2" version. I have checked on github repo and I find out current version of ng-admin is "1.0.7". But your repository is not using current version.

can you please share reason of behind it, because when I used current version of ng-admin, "MAGOWARE" repo does not work properly?

**Comment by eduardhasanaj2** [comment]
Hi @yaminipanchal 
Sorry for late reply. 
Sometime there are breaking changes so we cannot upgrade easily.
Current version should work flawlessly
