### ISSUE TITLE
VOD not working

### ISSUE THREAD

**Issue by shamar112** [MAGOWARE/backoffice-administration#27]
vod is not working in user applications, since this upgrade

**Comment by irisstaro** [comment]
Hello Shamar
As we also discussed via our support e-mail , the problem is resolved on the new update application we sent you

**Comment by yamcell** [comment]
I have same issue Please send us this New application or backoffice without this isues

**Comment by yamcell** [comment]
Hello we still have same vod problem after bigging stop few minutes later
Any advice
