### ISSUE TITLE
EpgData channels_id led to fail to create Epg

### ISSUE THREAD

**Issue by hungphidev** [MAGOWARE/backoffice-administration#28]
The error is in Epg Data > Create: Epg Data, error message is 

> Error: ( SequelizeValidationError, undefined, notNull Violation: channels_id cannot be null )

Cause: The **channels_id** is defined in _models\epg_data.js_ but not use in _public\build\main.js_ , it led to the object use for insert to database missing **channels_id** field.
Seem that Magoware use the **channel_number** instead. 

My temporature solution is assign the value of **channel_number** to **channels_id** before insert to database and it work well.

Please fix this issue in next update.

**Comment by irisstaro** [comment]
Hello !

Could you provide as an epg file you upload that shows this error please ?

Thanks
Iris

**Comment by hungphidev** [comment]
> Hello !
> 
> Could you provide as an epg file you upload that shows this error please ?
> 
> Thanks
> Iris

Hi @irisstaro . The error happend when I create epg data manually instead of upload file :)

**Comment by irisstaro** [comment]
Hello !

Please check the last update , included the EPG Create problem fixed
