### ISSUE TITLE
VOD Episode issue

### ISSUE THREAD

**Issue by hungphidev** [MAGOWARE/backoffice-administration#31]
Seem that VOD Episodes missing place to input or select parent VOD.

Additional, why you don't create a new table in database to store VOD Episode data, because vod title, description, IMDB, and other information belong to VOD. So that no need to input that information again in VOD Episodes.

**Comment by irisstaro** [comment]
Hello!

We are working on that and will be ready on the next update of the management system

**Comment by hungphidev** [comment]
> Hello!
> 
> We are working on that and will be ready on the next update of the management system

Great news @irisstaro !
