### ISSUE TITLE
Series

### ISSUE THREAD

**Issue by edizio** [MAGOWARE/backoffice-administration#32]
Series NOT FOUND in MAGOWARE BACKOFFICE

**Comment by irisstaro** [comment]
Hello Edizio
The TV Shows section on VOD is under development and will be launched soon

Regards

**Comment by ciscoterminal** [comment]
my database name is magoware 
2018-12-12T03:08:10.667Z - error: error reading database settings:
{ message: 'ER_NO_SUCH_TABLE: Table \'magoware.settings\' doesn\'t exist',
  name: 'SequelizeDatabaseError',
  stack: 'SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table \'magoware.settings\' doesn\'t exist\n

**Comment by irisstaro** [comment]
Does the database magoware already exist ?
If yes then run:
sudo node server.js sync (will sync all missing tables)

otherwise run:
sudo node server.js sync force (will wipe the database and recreate)
