### ISSUE TITLE
Fresh Install error -- { message: 'ER_NO_SUCH_TABLE: Table 

### ISSUE THREAD

**Issue by ciscoterminal** [MAGOWARE/backoffice-administration#33]
even tried on debian 9 also on ubuntu 16.04 and 18
npm version is 6.4.1 and node version is 8.14.0 mysql version is 5.7.24 and ubuntu 18.04
my database name is magoware after executing sudo node server.js
2018-12-12T03:08:10.667Z - error: error reading database settings:
{ message: 'ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist',
name: 'SequelizeDatabaseError',
stack: 'SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist\n

**Comment by hungphidev** [comment]
> even tried on debian 9 also on ubuntu 16.04 and 18
> npm version is 6.4.1 and node version is 8.14.0 mysql version is 5.7.24 and ubuntu 18.04
> my database name is magoware after executing sudo node server.js
> 2018-12-12T03:08:10.667Z - error: error reading database settings:
> { message: 'ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist',
> name: 'SequelizeDatabaseError',
> stack: 'SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist\n

Have you try to run command `sequelize db:migrate`?

**Comment by ciscoterminal** [comment]
yes sir , same error

**Comment by saimirg** [comment]
Does the database magoware already exist ?
If yes then run:
`sudo node server.js sync`  (will sync all missing tables)

otherwise run:
`sudo node server.js sync force`  (will wipe the database and recreate)

**Comment by penfolduk** [comment]
getting same as well 

If yes then run:
sudo node server.js sync (will sync all missing tables)

otherwise run:
sudo node server.js sync force (will wipe the database and recreate)

does nothing

**Comment by penfolduk** [comment]
got working using ubuntu 17.10 x64 sync worked as well
