### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE 

### ISSUE THREAD

**Issue by sazzam2** [MAGOWARE/backoffice-administration#35]
Can someone please assist me with this error I am getting when trying to start the server? 
<img width="1228" alt="11111" src="https://user-images.githubusercontent.com/33765573/50465743-6b16bb00-0956-11e9-8cce-74dcc8313730.PNG">

The admin panel works but unfortunately it does not allow me to get past the login screen. After entering the admin name and password it doesn't do anything.

<img width="1886" alt="sdgdsgfsd" src="https://user-images.githubusercontent.com/33765573/50466102-d19cd880-0958-11e9-9848-4565b2f6e606.PNG">

Error log  (./backoffice-administration/errors.log) is showing this error:
```
{"level":"error","message":"Error connecting to database","timestamp":"2018-12-27T02:04:16.322Z"}
{"message":"error reading database settings:","name":"
SequelizeConnectionError","stack":"SequelizeConnectionError: ER_NOT_SUPPORTED_AUTH_MODE: Client
does not support authentication protocol requested by server; 
consider upgrading MySQL client\n at Handshake.<anonymous>
```

**Comment by irisstaro** [comment]
Hello Sazzam!
The problem you are having is not directly  connected to our management system. Seems like the authentication mode used from you on MySQL is not valid for logging with username / password. Please check the MySQL setup on the server. Also make sure the user you are using for connection has the necessary rights

**Comment by graseuser** [comment]
> Can someone please assist me with this error I am getting when trying to start the server?
> <img alt="11111" width="1228" src="https://user-images.githubusercontent.com/33765573/50465743-6b16bb00-0956-11e9-8cce-74dcc8313730.PNG">
> 
> The admin panel works but unfortunately it does not allow me to get past the login screen. After entering the admin name and password it doesn't do anything.
> 
> <img alt="sdgdsgfsd" width="1886" src="https://user-images.githubusercontent.com/33765573/50466102-d19cd880-0958-11e9-9848-4565b2f6e606.PNG">
> 
> Error log (./backoffice-administration/errors.log) is showing this error:
> 
> ```
> {"level":"error","message":"Error connecting to database","timestamp":"2018-12-27T02:04:16.322Z"}
> {"message":"error reading database settings:","name":"
> SequelizeConnectionError","stack":"SequelizeConnectionError: ER_NOT_SUPPORTED_AUTH_MODE: Client
> does not support authentication protocol requested by server; 
> consider upgrading MySQL client\n at Handshake.<anonymous>
> ```

Login To ur sql  using mysql -u root -p 
and add that line 
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';
that fixe my probleme
