### ISSUE TITLE
Magoware App

### ISSUE THREAD

**Issue by jorslz** [MAGOWARE/backoffice-administration#36]
I just here to talk about the Magoware App.  I have some problem with the new version app that I would like you guys to know about it.
 
1-When I open the app in my Android TV box or Android Phone and I click Live tv I get a message pop up saying to ( confirm ) and when I click ( confirm ) the live tv closed automatically and I can’t do nothing. 

2-Also, in the Android App the application is not saving the server address, there is not option to click save user name details and server address.  In the IOS app these details I see is saved automatically. 
 
3-The Sign Up option is not working in the app, I added all my email details to the Magoware in my server but is not working the sign up option in the app, I get error message saying “ Email can’t send” when I am trying to sign up in the app.

4-In my iPhone IOS App I only can play 2 channels, the rest of the channels I get an error message ( Video cannot be Played ) but on my android phone or tv box all the channels play good without problem except now that in this new version I am getting the error that I explain in ( 1 ).
 
5- In some device the app wont even show up the icon in home menu after installation. It says it installs, but its nowhere to be found. I tried it on S8 and had the same problem. I tried on my second tv android box same problem.  If I look on Settings > Apps, the app is showing installed but is not way to run the app from there.

**Comment by jorslz** [comment]
![gnuwzilnsmscy84kfq2zjw](https://user-images.githubusercontent.com/46202811/50494800-75d35d80-09f3-11e9-8461-b1dbb0d88f2a.jpg)

**Comment by irisstaro** [comment]
Hello !
Please check the comments for all the issues raised : 

1-When I open the app in my Android TV box or Android Phone and I click Live tv I get a message pop up saying to ( confirm ) and when I click ( confirm ) the live tv closed automatically and I can’t do nothing.
Please confirm us the application version you are using

2-Also, in the Android App the application is not saving the server address, there is not option to click save user name details and server address. In the IOS app these details I see is saved automatically.
It is a configuration done from us, the server address is used only for testing purposes. To have the application branded with your server address is part of White Labeling Packages

3-The Sign Up option is not working in the app, I added all my email details to the Magoware in my server but is not working the sign up option in the app, I get error message saying “ Email can’t send” when I am trying to sign up in the app.

4-In my iPhone IOS App I only can play 2 channels, the rest of the channels I get an error message ( Video cannot be Played ) but on my android phone or tv box all the channels play good without problem except now that in this new version I am getting the error that I explain in ( 1 ).
Depends on the channels format you are using. IOS default player plays only HLS streams

5- In some device the app wont even show up the icon in home menu after installation. It says it installs, but its nowhere to be found. I tried it on S8 and had the same problem. I tried on my second tv android box same problem. If I look on Settings > Apps, the app is showing installed but is not way to run the app from there.
You need to check the device firmware, if it us STB firmware you need to use the STB application and download it from our web page. If it is android TV firmware, download the Smart TV application from playstore. 

Regards
Iris
