### ISSUE TITLE
Seperation of channels to category TV/RADIO/VOD

### ISSUE THREAD

**Issue by deku-m** [MAGOWARE/backoffice-administration#37]
As i was looking around in the webgui from the demo i didnt see the seperation of tv channels and radio channels. Because on the streams we capture there are also a channel list with radio channels in it, so different category. This will also bring a seperated icon for radio on the apps for tv/stb/mobile.
 Is this possible...?

**Comment by saimirg** [comment]
It is not currently possible to present radio channels on a separate icon on the main menu, but others are presenting radio channels differently. 
Radio channels can be considered as normal tv channels and listed on a separate category/genre, so user does not have to leave Live TV to listen to radio channels. And a more advanced option is to combine a radio/audio stream with a static image that represents the radio channel, so you dont get a black screen. But this has to be done on the encoder side.
