### ISSUE TITLE
"When application runs for the first time, it will automatically create database structures and populate necessary tables with default values."

### ISSUE THREAD

**Issue by ritabrain** [MAGOWARE/backoffice-administration#4]
Hello! 
I have installed your middleware, but it has not created  database structures. 
What is wrong?

**Comment by glalaj** [comment]
Hello,
When running for the first time, the application will prompt you to enter the database name, host, username and password. Can you verify that the credentials you entered for the database connection were correct? 
If yes, were there any messages displayed?
