### ISSUE TITLE
import m3u

### ISSUE THREAD

**Issue by includes08** [MAGOWARE/backoffice-administration#40]
Could you add a way to import m3u's? or is this already a thing and i don't know about it?

**Comment by irisstaro** [comment]
Hello!

The import of data's from m3u files is under development and will be ready within 2 - 3 weeks 

Regards

**Comment by joe350** [comment]
hello Guys, any update ?

**Comment by tangiro** [comment]
Hola buen dia

seria genial poder importar listas m3u, he tenido que hacer 100 canales manualmente, esta actualización seria genial... excelente programa...

**Comment by yamcell** [comment]
Tangiro. Una pregunta en el are vod las películas te funcionan bien pues a mi se reinicia la app luego de unos minutos y las series no se muestran

**Comment by tangiro** [comment]
Hola.
Yamcell
La verdad no he podido crear el menú carrusel en la última versión. Me sale un error el cual ya informe al soporte de magoware.
Estoy esperando respuesta.
Si puedes escríbeme x WhatsApp
571 3002333415

También te cuento que la app móvil se cierra cuando uso la búsqueda en el menú vod.
Gracias por escribir.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by yamcell** [comment]
Agregue tu número pero no me sale este es el mio +18094992525

**Comment by eduardhasanaj2** [comment]
At current version this feature is implemented
Please @irisstaro post a  link to doc and close this
