### ISSUE TITLE
incomplete install guide? on purpose?

### ISSUE THREAD

**Issue by Daigtas** [MAGOWARE/backoffice-administration#41]
hi. i am havin' a problem with the installation guide. By reading it there is absolutely no info what distro used, what versions used, what is requirements of the software that is has to be installed on the server prior to install this script. 
after following the instructions (preinstalled apache2, mysql, php and phpmyadmin before doing that), got to the point wher it has to be cloned from git to a webserver, again no info to what dir, by default put it to an /var/www/html, by pulling it out from backoffice-administration-master dir that is created while cloning. there are errors that it has to use port 80 by default and it is occupied by appache2 by default, so by going to /config/env/default.js and changing the port to any other it went ok. 
By the way the installer is not creating any databases it only connects to created one and puts own tables there, so it has to be created before running node server.js installer. 
after all of it i am at the point where the the default specifield /admin link is not working becouse it is in a public/admin subdir. and the application is sending the creditials to non exixting address... and again there is absolutely NO info whats so ever.  
question is: who wrote this install script and how many minutes it took to write it becouse it seems like it is written incomplete and lacking info. after reading the postpone where it is contacts and the price to install it... man, do you realy have to kill the project like that? give the tools, give the info give the working script and make the additions or corrections monetized... not the install..
anyways, looking forward and hoping that the info guide (manual install) or the auto installation script will be updated and all that crap ends here. So far the experience about this project is like a nightmare to install.
and i had way worse projects installed by digging in to the scripts and making own manual install guides but this time come on guys... do atleast SOME effort to make this project more popular. 
Open source power is in the community, more of it -> the more powerful the script gets, more contributions it gets, less bugs and etc.

**Comment by twisted-fire-starter** [comment]
did you manage to get this working pal ?? as i am having the same issue on where to have it all

**Comment by irisstaro** [comment]
Hello!

You can find a step by step installation guide on the below article:
https://magoware.freshdesk.com/a/solutions/articles/35000124356

Regards

**Comment by sajume** [comment]
Well the article suggest what @Daigtas requested its not a complete installation guide for something on complicated nodejs setup, I tried clean ubuntu and installed nodejs and npm has all sorts of discrepancies, no help, also tried a custom droplet(pre-installed nodejs) OS, which also ended same way.
When you run sudo node server.js  it goes on a long coma and ends up with network disconnect spend 3 days already with 5 new images.
There should be little more information for developers to look at and further collaborate.
Thanks.
