### ISSUE TITLE
Support for other smarttv`s like (LG) webOS

### ISSUE THREAD

**Issue by deku-m** [MAGOWARE/backoffice-administration#42]
Hi,

I saw android tv as smart tv`s is supported.. Is there any plan to add more smart tv`s for this application like webOS from LG.

**Comment by irisstaro** [comment]
Hello!

We will soon launch the application for Samsung & LG Smart TV-s. The application is under development

Regards

**Comment by tony7pt** [comment]
Will that app be available soon? price range? can it be costume branded?
