### ISSUE TITLE
Limit devices per login

### ISSUE THREAD

**Issue by tehnicki** [MAGOWARE/backoffice-administration#44]
Can you implement limited number of devices per Login Account? For now, with one Login Account, multiple devices can be connected at the same time. Perhaps unlimited.

**Comment by saimirg** [comment]
It is already implemented.
By default a subscriber can only login in one bigscreen device (box, androidtv) and one smallscreen device (android mobile, apple device) at the same time. 
Regardless of successful login, subscriber must have valid subscription on both. You can manage subscriptions separately for each device type or together.

**Comment by tehnicki** [comment]
I tried one subscription to 3 smartphones, with one login and it works without problems at everyone at the same time.

**Comment by tehnicki** [comment]
Can you tell me, how i can set to login 1 login per 1 device? I tested, and with 1 login and 1 subscribe, i can login to 5 smart phones and watch Live TV.

**Comment by saimirg** [comment]
Do you get a message on the screen of the  seccons device you login , that you already are loged in on another device ?

**Comment by tehnicki** [comment]
No. I never saw this message

**Comment by yamcell** [comment]
Same problem 1account 5device and all played

**Comment by hor4net** [comment]
Array `appids = [];`  is empty in code in file `credentials.server.controller.js.`  This array is using in where condition for finding active device in sql. 
```
models.devices.findOne({
                    where: {username: req.auth_obj.username, device_active: true, appid: {in: appids}}
                }).then(function (device) {
//if record is found then device is found
```
Record in this way can not be found. I add to array `appids = [1,2];`  1 and 2 are types of apps - Mobile and STB. Restart server.js. After that, a message for double login appears.
I'm not sure if this is the right way, but it works.

**Comment by yamcell** [comment]
I need to do this or u say you all ready do it?

**Comment by yamcell** [comment]
> 
> 
> Array `appids = [];` is empty in code in file `credentials.server.controller.js.` This array is using in where condition for finding active device in sql.
> 
> ```
> models.devices.findOne({
>                     where: {username: req.auth_obj.username, device_active: true, appid: {in: appids}}
>                 }).then(function (device) {
> //if record is found then device is found
> ```
> 
> Record in this way can not be found. I add to array `appids = [1,2];` 1 and 2 are types of apps - Mobile and STB. Restart server.js. After that, a message for double login appears.
> I'm not sure if this is the right way, but it works.

can u please show where u set or share code with thi sfix inside

**Comment by hor4net** [comment]
Hi, I already said. File is `credentials.server.controller.js.` Path `magoware/modules/deviceapiv2/server/controllers`.  Line 24:  `var appids = [];` change to `var appids = [1,2];` Restart server.js.

**Comment by yamcell** [comment]
How restart no de in Ubuntu commant line sir
And thanks in advance

**Comment by yamcell** [comment]
Hi Im edited files and same problem múltiple login with same User and Pass. Im change in table database to 1 device and 2 same problem never logout from firt device Please help us

**Comment by yamcell** [comment]
still have same issues 4 devices in same account , now show you are try to log need to sin out from another device but continue and never log out devices

**Comment by eduardhasanaj2** [comment]
Hi @yamcell 
This is fixed in the update we are going to launch soon.

**Comment by yamcell** [comment]
Massage come after edited but not logout devices and u can connect múltiple devicea
