### ISSUE TITLE
EPG MAP ID

### ISSUE THREAD

**Issue by tehnicki** [MAGOWARE/backoffice-administration#46]
EPG MAP ID is unique. If is used for some channel, no possible use to other channel. Maybe i want use ID: "No EPG" on more channels for CatchUp.

**Comment by irisstaro** [comment]
Hello @tehnicki!
Thank you for contacting Magoware. The EPG MAP ID is unique because it helps the management system recognize the EPG data allocated to a specific channel. 
For the channels you don't want to have EPG, you can leave blank the EPG MAP ID field

Regards
Iris

**Comment by yamcell** [comment]
We have problem with vod a section can u check
