### ISSUE TITLE
user permissions error: Cannot read property 'findOne'

### ISSUE THREAD

**Issue by hor4net** [MAGOWARE/backoffice-administration#47]
Hi, 
when i try to change APIs permissions for users i getting this error:
`{"level":"error","message":"TypeError: Cannot read property 'findOne' of undefined\n    at exports.update (/usr/local/src/magoware/modules/mago/server/controllers/grouprights.server.controller.js:44:13)\n    at Layer.handle [as handle_request] (/usr/local/src/magoware/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/src/magoware/node_modules/express/lib/router/route.js:137:13)\n    at next (/usr/local/src/magoware/node_modules/express/lib/router/route.js:131:14)\n    at Route.dispatch (/usr/local/src/magoware/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/local/src/magoware/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/src/magoware/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/local/src/magoware/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/src/magoware/node_modules/express/lib/router/index.js:275:10)\n    at serveStatic (/usr/local/src/magoware/node_modules/serve-static/index.js:75:16)\n    at Layer.handle [as handle_request] (/usr/local/src/magoware/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/src/magoware/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/src/magoware/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/src/magoware/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/src/magoware/node_modules/express/lib/router/index.js:275:10)\n    at hsts (/usr/local/src/magoware/node_modules/hsts/index.js:52:5)","timestamp":"2019-03-29T11:54:45.210Z"}`

**Comment by hor4net** [comment]
I added manual permissions to sql, and now all permissions for the admin user are enabled

**Comment by hor4net** [comment]
I added manual permissions to sql, and now all permissions for the admin user are enabled. [img](https://imgur.com/a/i9Mo3WT) but API post always returns {"message":"User is not allowed"}.  similar to [this ](https://github.com/MAGOWARE/backoffice-administration/issues/19) . I'm using the latest version clean install
ubuntu - 16.04.6 LTS
node - v8.15.1
MySQL - 5.7.25
+------------------------+
| @@sql_mode             |
+------------------------+
| NO_ENGINE_SUBSTITUTION |
+------------------------+
Can you help me with this?

**Comment by irisstaro** [comment]
Hello @hor4net 
Please receive the new update of the management system and test again the issue

Regards
