### ISSUE TITLE
Blank Screen!

### ISSUE THREAD

**Issue by knightfall** [MAGOWARE/backoffice-administration#5]
I did a test installation of magoware backoffice administration. When I log in as a client from an Android smartphone, the screen goes blank. But the app works perfectly with the demo backoffice administration.

**Comment by irisstaro** [comment]
Hello!
On the backoffice administration you installed , go to Company Settings menu , and edit the field 
Assets Url : "http://your_IP_address"
Try to clear data on the application side and re-login

**Comment by knightfall** [comment]
Thank you. It worked like a charm!.

**Comment by irisstaro** [comment]
You are welcome

**Comment by deganza** [comment]
Hi Iris
I've the same problem. But the screen stays blank even If I adapt the Assets Url.
What can I do? I've the installed the magoware-2.8.17.apk
