### ISSUE TITLE
Few Issues related to login

### ISSUE THREAD

**Issue by subbutvl** [MAGOWARE/backoffice-administration#58]
1. After installation could not login, tried different with different browsers but not able to login.
2. The I tried node server.js sync force, after this I try to login but I am getting error message saying that "Company is blocked due to Payment issues"...
3. After that I tried to duplicate the admin user and change the name and group policy to superadmin, now i am able to login but i could not do other than monitor the users, usergroups and company details.

**Comment by alonzo313** [comment]
Use Opera browser

**Comment by yamcell** [comment]
Any one could set tba show property in backoffice Im never get done this área. In Last update TV show póster can view in User side but never season or episode Please any advice thanks in asvance

**Comment by alonzo313** [comment]
Will look into it.. Question? Did you have issue linking your server and connecting apk to panel?

**Comment by fabgsouza76** [comment]
Tried to login with admin/admin and getting "Company is blocked due to Payment issues"...
Please someone advise.

**Comment by subbutvl** [comment]
> Will look into it.. Question? Did you have issue linking your server and connecting apk to panel?

No i did not try that, will check and revert back.

**Comment by irisstaro** [comment]
Hello @fabgsouza76 
To resolve the issue you are having, please update the value on table settings billing_date
After updating the value, restart the service and you should be able to login

**Comment by irisstaro** [comment]
Hello @alonzo313 
What issue are you having on connecting the application to your local server?

**Comment by fabgsouza76** [comment]
There is no field **billing_date** on table **settings.** 
Please advise again.

**Comment by alonzo313** [comment]
Good morning Iris, I have input url and attempted to link server several
times to STB apk. Each time it was unresponsive

**Comment by yamcell** [comment]
Try to log from stb app and mobile and say User not found or 0 not found

**Comment by yamcell** [comment]
no value on table settings billing_date

**Comment by alonzo313** [comment]
What Stb apk is functional. I am having difficulty linking panel to working
apk

**Comment by yamcell** [comment]
16 days and billing date not found

**Comment by irisstaro** [comment]
Hello!

You can receive the new update for the billing date where we have set a default value
This will resolve the issue you are having with login and be able to login
