### ISSUE TITLE
Error Connecting DB

### ISSUE THREAD

**Issue by armaghanshahzad** [MAGOWARE/backoffice-administration#6]
2017-11-05T17:16:09.897Z - error: Error connecting to database
{ SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306

**Comment by irisstaro** [comment]
Hello!
Probably you haven't enter database information correctly, and you receive this error. 
You can try to delete "config" file , copy it again and try to connect to the database you have created in MySQL. When you enter database information in "database host" we would recommend enter : localhost as value

**Comment by armaghanshahzad** [comment]
Hi,

The main problem is that the installation script \backoffice-administration-master\config\env\db.connection.js tries to install the portal in mysql but mysql is not known to the installation. I tried to install mysql locally on the server but with no luck. I tried also to "npm install mysql" but no luck.

 I changed the above file to point to "sqlite" before the installation starts. It worked and then I logged on the server but half of the things does not work with in portal (useless). This is quite buggy installation + procedure which does not work out of the box.  Please try on a clean box to reproduce the errors. I have tried the installation on Redhat + ubuntu but the result is the same.

I think may there are some major part missing in the installation guide or some prequisite for the installation. For example: if you look the the db.connection.js file it points to mysql servver by default but there is no information about the mysql server installation through npm, if it is install then server.js doesnot checks that or try to connect to the server.

**Comment by armaghanshahzad** [comment]
I got the solution. (I am installing on Redhat and also valid for Centos/Fedora)
**Mariadb/Mysql server must be installed before you continue.** 

# git clone https://github.com/MAGOWARE/backoffice-administration.git
# cd backoffice-administration/
# npm install
#  mysql
MariaDB [(none)]> create database magoware;
Query OK, 1 row affected (0.00 sec).
# node server.js
entering first function
sync =  undefined
force =  undefined
Please enter database information below :
Enter database username:  root
Enter database password:
Enter database host address:  localhost
Enter database name:  magoware
Configuration file saved !
----------------------------
Logon to http://server-ip
username: admin
Password:admin

Now you can start using/testing Magoware

I hope this will help anyone trying to install MAGOWARE.

Regards
Armaghan
