### ISSUE TITLE
Magoware detailed documentation

### ISSUE THREAD

**Issue by fabgsouza76** [MAGOWARE/backoffice-administration#60]
Is there an actual Magoware documentation.
Like a Admin manual or something. 
Things are very confusing.
I have the system installed and running but i cannot find any documentation that explains the modules and what things mean. 
Please if  someone knows of any detailed documentation for the system, let me know.
It seems powerful but with no documentation is becoming difficult to work with.

**Comment by irisstaro** [comment]
Hello @fabgsouza76 
The documentation we provide is for the setup since most of the modules are widely used and the management system is very intuitive. 
However, we will be more than happy to assist you with the questions you might have for the middleware
