### ISSUE TITLE
TV Channels

### ISSUE THREAD

**Issue by TrevorPi** [MAGOWARE/backoffice-administration#61]
Error registering Categories / Genre and Channels and Streams in Live TV Channels submenu. Link creation does not work. Could anyone help with this problem?

**Comment by irisstaro** [comment]
Hello @TrevorPi 
To resolve the issue set the MySQL mode to 'NO_ENGINE_SUBSTITUTION'
After setting the mysql mode reload the url and you will be able to create channels and categories

Regards
