### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by twisted-fire-starter** [MAGOWARE/backoffice-administration#62]
i have a login issue i have just installed it for the first time but keep getting a error every time i try to login it keeps saying Company disabled due to payment can someone please help i have had a read through the issues to see if there was any fixes and i cannot find the billing_date in table settings so please can someone advise thanks in advance

**Comment by datagti** [comment]
Same problem.

**Comment by Goeks1** [comment]
I have also hit in the same problem

**Comment by yamcell** [comment]
> expire_date
it this the correct way? pleae tell us

expire_date` datetime NOT NULL '3018-01-01 00:00:00',

**Comment by eduardhasanaj2** [comment]
I am closing the issue as @yamcell pointed out the solution to this problem.
