### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by IPTVadmin** [MAGOWARE/backoffice-administration#65]
Are there any directions on how to upgrade Magoware. Not sure what version I'm running.

**Comment by eduardhasanaj2** [comment]
@irisstaro Please give to @IPTVadmin the upgrade doc

**Comment by irisstaro** [comment]
Hello @IPTVadmin 
Please find on the below link the upgrade process: 
https://magoware.freshdesk.com/a/solutions/articles/35000141337
