### ISSUE TITLE
Máx Multi login 

### ISSUE THREAD

**Issue by yamcell** [MAGOWARE/backoffice-administration#69]
Hello im read in github.com this same problem and i fo all the another guys say to resolve but same problem

I set 2  and 1 Account in Multi login para meter but with same Account can log in all cell Phone or box o want, the info about you are try to log in another device shows but never log out from older device all devices continúe working how can fix this in code and make log out if try to log in múltiple devices

**Comment by eduardhasanaj2** [comment]
Hi
Unfortunately the release of the update was postponed because some other related work.
When the next update is released, this will be fixed.
