### ISSUE TITLE
Mobile app does not show nothing

### ISSUE THREAD

**Issue by eduardomunizbarreto** [MAGOWARE/backoffice-administration#7]
Hi, I followed the instructions to configure the server, successed log in to the server with the smartphone app, but the app show a black screen.
The only information shown is the username, the version and an information: "No subscription". I followed the instructions of the magoware.tv.
Can you help me?

Thanks.

**Comment by irisstaro** [comment]
Hello!
In the Company settings menu, please check the field Assets URL . The value needs to be : http://your_server_IP
After saving this change in the backoffice , re-login in application
