### ISSUE TITLE
how to create database??

### ISSUE THREAD

**Issue by shafwanaw** [MAGOWARE/backoffice-administration#76]
I was able to do the server.js node, then I was confused about how to create it for the database, and for what sequalize db : migrasi

**Comment by irisstaro** [comment]
Hello @shafwanaw 
You need to install the MySQL on the server or in another instance depending on your requirements, create a blank database and then link the magoware system with the created database.

Regards
Iris

**Comment by shafwanaw** [comment]
> Halo @shafwanaw
> Anda perlu menginstal MySQL di server atau dalam contoh lain tergantung pada kebutuhan Anda, buat database kosong dan kemudian tautkan sistem magoware dengan database yang dibuat.
> 
> Salam
> Iris
how to connect the magoware system with the database, after I give the command node server.js magoware directly stack and there is writing ECONNREFUSED
