### ISSUE TITLE
OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by havran99** [MAGOWARE/backoffice-administration#83]
Hi, when running node server.js, I get this error:
2019-11-01T16: 29: 40.014Z - Error: Error starting redis server
{message: 'OAuth2Strategy requires a clientID option',
  stack: 'TypeError: OAuth2Strategy requires a clientID option \ n at Strategy.OAuth2Strategy (/home/mega/node_modules/passport-oauth2/lib/strategy.js:86:34)\n at new Strategy (/ home / mega / node_modules) /passport-google-oauth20/lib/strategy.js:52:18)\n at Object.exports.init (/home/mega/modules/users/server/controllers/google_auth.server.controller.js:17:18 ) \ n at module.exports (/home/mega/modules/users/server/routes/user_provider.server.routes.js:6:16)\n at /home/mega/config/lib/express.js:279 : 41 \ n at Array.forEach (<anonymous>) \ n at Object.module.exports.initModulesServerRoutes (/home/mega/config/lib/express.js:278:32) init (/home/mega/config/lib/express.js:422:10)\n at /home/mega/config/lib/app.js:30:21 \\ at server.open (/ home / mega / config / lib / redis.js: 107: 13 \ n at promise.then (/home/mega/node_modules/redis-server/RedisServer.js:413:22)\n at <anonymous> \ n at process._tickCallback (internal / process / next_tick.js: 188: 7)

I don't know how else.

**Comment by havran99** [comment]
no and support silence

**Comment by irisstaro** [comment]
Hello @havran99 
Please receive the new update launched today to resolve the issue 

Regards

**Comment by cheyennemack22** [comment]
under cd backoffice-administration$ apt install npm  0r Sudo install npm  .... then run sudo node server.js
