### ISSUE TITLE
Magoware Error starting redis server

### ISSUE THREAD

**Issue by graseuser** [MAGOWARE/backoffice-administration#88]
This is The Output Of node server.js :

-------------------------------------Starting server----------------------------------------------------
2019-12-22T19:38:34.333Z - info: Initializing Sequelize...
2019-12-22T19:38:35.024Z - info: Finished Connecting to Database
2019-12-22T19:38:35.029Z - info: Initializing Stack...
2019-12-22T19:38:35.193Z - error: Error starting redis server 
{ message: 'Address already in use',
  stack: 'Error: Address already in use\n    at Function.parseData (/home/backoffice-administration/node_modules/redis-server/RedisServer.js:167:22)\n    at Socket.dataListener (/home/backoffice-administration/node_modules/redis-server/RedisServer.js:237:38)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:559:20)',
  code: -1 }
 netstat -tlnp | grep "6379"
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1232/redis-server 1 

there is no other process use the same port. can you please help me with that.

Thanks

**Comment by galaxynpm54** [comment]
graseuser can you solve it,
i'm also face redis issue,
if you can then update how to do it

**Comment by eduarhasanaj** [comment]
@galaxynpm54 please send us config files found in config/env.
Did you tried to see what is running on that port?
@graseuser did you try with sudo to get the left of processes

**Comment by galaxynpm54** [comment]
Thank you for your response. reinstall server with Debian 10.
now start server.
where can i get management documents. I will be very thankful to you. if
you can.

Sohrab Khan

**Comment by eduarhasanaj** [comment]
@galaxynpm54 https://magoware.freshdesk.com/support/home

@graseuser  Did you solve the problem?
I am cosing this for now.
