### ISSUE TITLE
tv box app showing "Player closing" message

### ISSUE THREAD

**Issue by eduardomunizbarreto** [MAGOWARE/backoffice-administration#9]
Hi, 
In company settings in backoffice, has a field "Activity Time Out". This time is in seconds?
How can I disable this option?

**Comment by irisstaro** [comment]
Hello Eduardo!

This filed determines when application return to main menu after innacticity time. The time is calculated in seconds and can not be disabled.
You can change the value to a longer time , for example 7200 (2 hours)
Note : this field is also used in login account settings , so try to change the value there too

**Comment by eduardomunizbarreto** [comment]
Alright thanks.
