### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by zyztek** [MAGOWARE/backoffice-administration#94]
Hi, i was wondering if you can help me whit the instalation process, because im new on this, i would like to install magoware on ubuntu 18...can you help me whit a tutorial, guide, help, or any thing please, thank you for your time and help.....

**Comment by eduarhasanaj** [comment]
Hi @zyztek 
You can clone this repository and enter in it in terminal.
Then you will type sudo node server.js
In the first run you will be required to enter your mysql server credentials and database name.
For more detailed guide please visit https://magoware.freshdesk.com/support/home
